newplayerwelcomemessage: welcome to the server, enjoy!

scoreboard:
  scoreboardtitle: "&1-----ScoreBoard-----"
  scoreboardline1: "&bIn-game Name: &a&o%player%"
  scoreboardline2: "&bBalance: &a&o$%balance%"
  scoreboardline3: "&bno"
  scoreboardline4: "&bgg"
  scoreboardline5: "&bhh"
  scoreboardline6: "&a%motd%"

messages:
  nonicknamegiven: "&cThis is not a valid nickname!"
  reloadplugin: "&aPlugin reloaded"
  invalidcommand: "&cInvalid Command!"
  nopermission: "&cYou do not have permission to use %command%!"
  nomessagegiven: "&cYou did not include a message!"
  nouser: "&cNo user provided"
  playeroffline: "&c%player% is not online"
  invaliduser: "&cInvalid user!"
  invalidreason: "&cInvalid reason!"
  playerafk: "&3%player% is currently afk."
  playernotafk: "&3%player% is not afk."
  youareafk: "&3You are currently afk."
  youarenotafk: "&3You are no lonegr afk."
  vanish: "&aYou are now in vanish!"
  playerjustvanished: "&a%player% just vanished!"
  playerjustunvanished: "&a%player% just unvanished!"
  unvanish: "&a You are no longer in vanish!"
  fix: "&3Fixed &a%helditem% &3for $5000"
  notenoughmoney: "&cYou do not have enough money to do this!"
  spawnset: "&a You have set the current spawn point to: %x, %y%, %z%"