name: coreintegrals
version: 1.2.3
main: me.shrob.CoreIntegrals
api-version: 1.19
description: CoreIntegrals is a plugin for all of your servers essential commands, and needs!

commands:
  balance:
    aliases:
      - bal
    description: displays players balance
  sudo:
    description: makes another player say something
  broadcast:
    description: broadcasts a message to the server
  broadcasthelp:
    description: broadcast help menu
  screenbroadcast:
    description: Broadcasts a message onto everybodies screen
  help:
    description: disabled the default help command
  clearchat:
    description: clears the ingame chat
  setMotd:
    description: sets the Motd of the server
  motd:
    description: sends the motd of the server
  gamem:
    description: commands for my ChangeGamemodeGUI
  editperms:
    description: Commands for the custom Permissions menu
  heal:
    description: Heals a player
  feed:
    description: Feed a player
  back:
    description: Teleports a player to their last location
  ban:
    description: bans a specific user
  setunbreakable:
    description: sets held item to unbreakable
  fix:
    description: fixes the item you're holding
    aliases:
      - repair
  staffhelp:
    description: help menu for all staff perks.
  staffchat:
    aliases:
      - staffc
      - sc
      - staffmsg
      - staffm
      - sm
    description: custom staff chat
  god:
    description: makes a player invulnerable
  invsee:
    description: open and edit a players inventory.
  kits:
    description: server kits for players.
  enderchest:
    aliases: [ec]
    description: opens another players enderchest
  openenderchest:
    aliases: [oec]
    description: opens your own ender chest
  freeze:
    description: freezes a player
  nickname:
    aliases: [nick]
    description: sets a players nickname
  realname:
    description: tells you the real ign of a user
  cireload:
    description: reloads the plugin config
  workbench:
    description: opens a crafting table through a command
  enchantingtable:
    description: opens an enchanting table through a command
  cenchant:
    description: allows enchanting above the usual minecraft level
  fly:
    description: sets the player to fly
  money:
    description: allows for changes within peoples balances
  debugstick:
    description: gives a player a debugstick
  barrier:
    description: gives a player a barrier
  lightblock:
    description: gives a player a lightblock
  gamemodesurvival:
    description: sets a user to gamemode survival
    aliases:
      - gms
      - gamemodes
      - gmsurvival
  gamemodecreative:
    description: sets a user to gamemode creative
    aliases:
      - gmc
      - gamemodec
      - gmcreative
  gamemodespectator:
    description: sets a user to gamemode spectator
    aliases:
      - gmsp
      - gamemodesp
      - gmspectator
  gamemodeadventure:
    description: sets a user to gamemode adventure
    aliases:
      - gma
      - gamemodea
      - gmadventure
  vanish:
    description: hides a player from everyone except someone with the vanish permission
    aliases:
      - v

permissions:
  coreintegrals.*:
    default: op
    description: operator access to the plugin
  coreintegrals.reload:
    description: reloads config file
    default: op
  coreintegrals.commands.gamemode.opengui:
    description: opens the gui for the gamemode change
    default: op
  coreintegrals.commands.gamemode.changegamemode:
    description: permission to use the gamemode changing commands
    default: false
  coreintegrals.commands.gamemode.*:
    description: permission to all custom gamemode commands
    default: op
  coreintegrals.misc.motd.set:
    description: set the servers motd
    default: false
  coreintegrals.misc.motd.*:
    description: permission to all motd commands
    default: op
  coreintegrals.commands.broadcast:
    description: permission to broadcast on the server
    default: false
  coreintegrals.commands.broadcast.screen:
    description: permission to broadcast a message on everybodies screen#
    default: op
  coreintegrals.commands.helpingplayers.back:
    description: teleports a player to their last location
    default: true
  coreintegrals.commands.helpingplayers.feed:
    description: feeds a player
    default: op
  coreintegrals.commands.helpingplayers.heal:
    description: heals a player
    default: op
  coreintegrals.commands.helpingplayers.openenderchest:
    description: opens your enderchest
    default: true
  coreintegrals.commands.staff.enderchest:
    description: opens a players enderchest
    default: op
  coreintegrals.commands.staff.punishments.ban:
    description: bans a player
    default: op
  coreintegrals.commands.staff.punishments.kick:
    description: kicks a player
    default: op
  coreintegrals.commands.staff.punishments.mute:
    description: mutes a player
    default: op
  coreintegrals.commands.staff.staffchat:
    description: permission to access the mc staff chat
    default: op
  coreintegrals.commands.permissions.openpermissionmenu:
    description: permission to open and use the permission menu
    default: op
  coreintegrals.commands.helpingplayers.god:
    description: makes a player Invulnerable
    default: false
  coreintegrals.commands.staff.invsee:
    description: opens the inventory of a fellow player to edit
    default: false
  coreintegrals.kits.selectkit:
    description: opens the inventory to select your custom kit
    default: true
  coreintegrals.kits.managekits:
    description: Manage custom kits
    default: false
  coreintegrals.kits.editkits:
    description: Edit custom kits
    default: false
  coreintegrals.kits.createkits:
    description: Create custom kits
    default: false
  coreintegrals.commands.staff.punishments.freeze:
    description: freeze a player
    default: op
  coreintegrals.commands.funstuff.nickname:
    description: sets a players nickname
    default: false
  coreintegrals.commands.useful.realname:
    description: tells a user the real ign of a player
    default: true
  coreintegrals.commands.useful.workbench:
    description: opens a crafting table through a command
    default: true
  coreintegrals.commands.useful.enchantingtable:
    description: opens an enchanting tavble through a command
    default: true
  coreintegrals.commands.useful.unbreakable:
    description: sets the held item to unbreakable
    default: op
  coreintegrals.commands.useful.fix:
    description: fixes the item you're holding
    default: false
  coreintegrals.commands.items.debugstick:
    description: gives a player a debugstick
    default: op
  coreintegrals.commands.items.barrier:
    description: gives a player a barrier
    default: op
  coreintegrals.commands.staff.vanish:
    description: hides the player from everyone except who has the vanish permission
    default: op
  coreintegrals.commands.helpingplayers.fly:
    description: sets the player to fly
    default: true
  coreintegrals.commands.staff.sudo:
    description: makes another player say something
    default: op