name: JoeyEssentials
version: 1.1.0
main: me.joeyessentials.JoeyEssentials
api-version: 1.18
description: Plugin For My own stuff

commands:
  broadcast:
    description: broadcasts a message to the server
  broadcasthelp:
    description: broadcast help menu
  screenbroadcast:
    description: Broadcasts a message onto everybodies screen
  help:
    description: disabled the default help command
  clearchat:
    description: clears the ingame chat
  setMotd:
    description: sets the Motd of the server
  motd:
    description: sends the motd of the server
  gamem:
    description: commands for my ChangeGamemodeGUI
  joeypermissions:
    description: Commands for the custom Permissions menu
  heal:
    description: Heals a player
  feed:
    description: Feed a player
  back:
    description: Teleports a player to their last location
  ban:
    description: bans a specific user
  staffhelp:
    description: help menu for all staff perks.

permissions:
  joeyessentials.gamem.opengui:
    description: opens the gui for the gamemode change
    default: op
  joeyessentials.gamem.*:
    description: permission to all custom gamemode commands
    default: op
  joeyessentials.motd.set:
    description: set the servers motd
    default: false
  joeyessentials.motd.*:
    description: permission to all motd commands
    default: op
  joeyessentials.broadcast:
    description: permission to broadcast on the server
    default: false
  joeyessentials.commands.helpingplayers.back:
    description: teleports a player to their last location
    default: true
  joeyessentials.commands.helpingplayers.feed:
    description: feeds a player
    default: op
  joeyessentials.commands.helpingplayers.heal:
    description: heals a player
    default: op
  joeyessentials.commands.staff.punishments.ban:
    description: bans a player
    default: op
  joeyessentials.commands.staff.punishments.kick:
    description: kicks a player
    default: op
  joeyessentials.commands.staff.punishments.mute:
    description: mutes a player
    default: op



